language: android
jdk: oraclejdk8
dist: trusty
android:
  components:
    # android sdk
    - android-28
    - build-tools-28.0.3
    - tools
    - platform-tools

    # additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository

    # system image
    - sys-img-x86-android-28
#before_script:
#script: